import Head from "next/head";
import { Inter } from "next/font/google";
import { useQuery } from "@apollo/client";
import { GET_POST } from "../graphql/query";
import GetPostModel from "@/models/GetPostModel";
import Layout from "@/components/Layout";
import Card from "@/components/Card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { loading, data } = useQuery(GET_POST);

  console.log("data", data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Layout>
          <div className="cardContainer">
            {data?.getPost?.map((item: GetPostModel) => {
              return (
                <Card
                  id={item.id}
                  key={item.id}
                  description={item.description}
                  title={item.title}
                />
              );
            })}
          </div>
        </Layout>
      </>
    </>
  );
}
