import Head from "next/head";
import { Inter } from "next/font/google";
import { useQuery } from "@apollo/client";
import { GET_POST } from "../graphql/query";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { loading, data } = useQuery(GET_POST);

  console.log("data", data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data?.getPost?.map((item) => {
          return (
            <div>
              <p>{item.title}</p>
            </div>
          );
        })}
      </main>
    </>
  );
}
